name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_IMAGE_NAME }}:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Update Kubernetes Deployment Image
        run: |
          kubectl set image deployment/ecom-web web=${{ secrets.DOCKER_IMAGE_NAME }}:latest --record
          kubectl rollout status deployment/ecom-web
